### ISSUE TITLE
Can't connect to Neo4j after update from 3.0 to 3.1

### ISSUE THREAD

**Issue by neildsouza** [florinpatrascu/neo4j_sips#19]
Hi,

I can't seem to connect to Neo4j after updating from 3.0 to 3.1.
The errors I get are ...
```elixir
** (Mix) Could not start application p8: P8.start(:normal, []) returned an error: shutdown: failed to start child: P8.ServiceSup
    ** (EXIT) shutdown: failed to start child: P8.Services.Neo4j
        ** (EXIT) an exception was raised:
            ** (ArgumentError) argument error
                :erlang.binary_to_existing_atom("bolt", :utf8)
                (poison) lib/poison/parser.ex:114: Poison.Parser.object_name/2
                (poison) lib/poison/parser.ex:95: Poison.Parser.object_pairs/4
                (poison) lib/poison/parser.ex:37: Poison.Parser.parse/2
                (poison) lib/poison/parser.ex:51: Poison.Parser.parse!/2
                (neo4j_sips) lib/neo4j_sips/server.ex:96: Neo4j.Sips.Server.init/1
                (neo4j_sips) lib/neo4j_sips.ex:57: Neo4j.Sips.start_link/1
                (p8) lib/p8/services/neo4j.ex:13: P8.Services.Neo4j.init/1
```

I have updated Neo4j.Sips to the latest version using
```
mix deps.update --all
```
But still no luck :(

Any help would be greatly appreciated.

Thnx in advance,

Neil.

**Comment by florinpatrascu** [comment]
Can you please show your Neo4j.Sips config file, fore brevity?!

**Comment by florinpatrascu** [comment]
Asking for the config file because I'm afraid you're trying to use the bolt protocol with Neo4j.Sips

**Comment by neildsouza** [comment]
Here is the __config.exs__ file
```elixir
# This file is responsible for configuring your application
# and its dependencies with the aid of the Mix.Config module.
use Mix.Config

config :neo4j_sips, Neo4j,
    url: "http://localhost:7474",
    pool_size: 5,
    max_overflow: 2,
    timeout: 30
```

**Comment by neildsouza** [comment]
Actually I haven't really tried the __Bolt__ connection yet.
Don't even know what setting to change in Neo4j.Sips to be honest.

**Comment by florinpatrascu** [comment]
Hmm ... it looks from the error you pasted initially, that there is a bolt atom mentioned, this is why I asked for the config file. I'll try on my local in a bit, as soon as I get near a computer. However, if you're planning to use Bolt, then you should check my other project: bolt_sips

**Comment by florinpatrascu** [comment]
Oh, one more thing: can you connect with a browser to the instance referenced by your config file? I.e. Same: host, port number, ...

**Comment by neildsouza** [comment]
Actually I don't plan on trying Bolt coz it's too new.
Shall let it bake for a few versions and then take a look see.
I had initially tried one of the node-js drivers from Neo4j and that didn't work out well.

**Comment by neildsouza** [comment]
Yes ... Can connect via the browser to the same host:port

**Comment by florinpatrascu** [comment]
Cool, good to know. Ok, I'll check this setup on my local, in 20-30 minutes.

**Comment by neildsouza** [comment]
Thnx so much.

**Comment by neildsouza** [comment]
Heyy ... really sorry but please ignore this.
I had not disabled security auth in neo4j.conf
```
dbms.security.auth_enabled=false
```
After doing that all is well.

Really sorry for the trouble but the Bolt msg and the Neo4j Svr upgrade threw me off.

See ya.

**Comment by florinpatrascu** [comment]
Hey no problem, glad you figured that out, thank you for letting me know. Cheers!!

Florin
(mobile)

**Comment by neildsouza** [comment]
Ok ... this is really embarassing.
Sorry to say that the problem hasn't gone away.
I had tested with a previous version of Neo4j ie. < 3.1 and reported that as working.
Really sorry about this but have to re-open this as a pending issue.

**Comment by florinpatrascu** [comment]
Hey no problem, the issue was at my end, I didn't expect to receive the `bolt` key from the server, during the initial handshake; details in the latest CHANGELOG

Please pull `0.2.14`, from: [Hex.pm/packages/neo4j_sips](https://hex.pm/packages/neo4j_sips), and check it out. HTH - Florin

**Comment by neildsouza** [comment]
Awesome ... that worked.
Thnx so much.
