### ISSUE TITLE
Models: how to create properties on relationships

### ISSUE THREAD

**Issue by asarode** [florinpatrascu/neo4j_sips#3]
Is is possible to add properties to relationships when creating a node via models?

``` elixir
Person.create(name: "Jane DOE", email: "jane.doe@example.com",
                                   age: 25, enable_validations: true, doe_family: true,
                                   married_to: john)
```

In this example, I'd want to add a `since` property on the married_to relationship.

**Comment by florinpatrascu** [comment]
Not yet, sorry.

**Comment by florinpatrascu** [comment]
trying to find a friendly syntax for this, any suggestions?

**Comment by asarode** [comment]
Maybe something like

``` elixir
Person.create(married_to: %{model: john, properties: %{since: "right meow"})
```

I haven't used too many Elixir libraries yet so idk if that's idiomatic. It's what seems familiar from my JS background.

**Comment by florinpatrascu** [comment]
the development for supporting the Models will happen here: [neo4j_sips_models](https://github.com/florinpatrascu/neo4j_sips_models).
