### ISSUE TITLE
Basic auth doesn't seem to work properly?

### ISSUE THREAD

**Issue by johnhamelink** [florinpatrascu/neo4j_sips#5]
Hi there,

I’m using `neo4j_sips` for an elixir project I’m trying to get into production currently. The last thing stopping me from getting the project into production is basic auth with `neo4_sips` - no matter what I try, the server seems to come back as unauthorized.

I’m already using the same config with a ruby API using `neo4jrb`, so I know that the credentials are correct. 

Futhermore, if I use curl to access the Neo4j API in the format of “http://<username>:<password>@host” then I get past authorization. Turning off the auth requirement on the server also allows me to connect.

Has this feature been used successfully elsewhere?

I'm using Neo4j enterprise 2.3.2

Best,
JH

---
### prod.exs:

``` elixir
config :neo4j_sips, Neo4j,
  basic_auth: [
    username: "neo4j",
    password: "<password>"
  ],
  url: "http://<host>:7474",
  pool_size: 5,
  max_overflow: 2,
  timeout: 30
```

```
ubuntu@10:~$ sudo -u www-data /opt/app/api/bin/api console
Using /opt/app/api/releases/0.0.11/api.sh
Exec: /opt/app/api/erts-7.2/bin/erlexec -boot /opt/app/api/releases/0.0.11/api -boot_var ERTS_LIB_DIR /opt/app/api/erts-7.2/../lib -env ERL_LIBS /opt/app/api/lib -config /opt/app/api/running-config/sys.config -pa /opt/app/api/lib/api-0.0.10/consolidated /opt/app/api/lib/api-0.0.11/consolidated -args_file /opt/app/api/running-config/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /opt/app/api
/opt/app/api
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

{"Kernel pid terminated",application_controller,"{application_start_failure,neo4j_sips,{{shutdown,{failed_to_start_child,neo4j_sips_pool,{{badmatch,{error,{bad_return_value,{error,<<\"Cannot connect to the server at url: http://<host>:7474. Reason: Invalid Authorization\">>}}}},[{poolboy,new_worker,1,[{file,\"src/poolboy.erl\"},{line,275}]},{poolboy,prepopulate,3,[{file,\"src/poolboy.erl\"},{line,296}]},{poolboy,init,3,[{file,\"src/poolboy.erl\"},{line,145}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}},{'Elixir.Neo4j.Sips',start,[normal,[]]}}}"}

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,neo4j_sips,{{shutdown,{failed_to_start_child,neo4j_sips_pool,{{badmatch,{error,{bad_return_value,{error,<<"Cannot connect t
```

**Comment by florinpatrascu** [comment]
Hi John - it should work, but let investigate this issue against the Neo4j version that you have over there. The authentication, basic and token-based, was one of the first functions I implemented and didn't have any issues with, but I'll check again. There is at least one (public) project that is using the auth: https://github.com/asarode/thoughtshare, and a couple of private ones, and didn't receive any troubling reports until now. Also, are you sure your app runs in prod mode, i.e. $ MIX_ENV=prod ... ?

**Comment by florinpatrascu** [comment]
I just tried, using Neo4j 2.3.3 (Community) with the code from the master branch, and it works. My local server is configured to listen to localhost:7373. The config I am using:

```
config :neo4j_sips, Neo4j,
  basic_auth: [
    username: "neo4j",
    password: "******"
  ],
  url: "http://localhost:7373",
  pool_size: 5,
  max_overflow: 2,
  timeout: 30
```

I also enabled the Neo4j experimental login support, and below are the relevant log records.

Without authentication (using a wrong password, on purpose):

```
127.0.0.1 - - [24/Jan/2016:11:12:22 -0500] "GET /db/data/ HTTP/1.1" 401 135 "
==req== GET /db/data/ HTTP/1.1
Authorization: Basic bmVvNGo6c3dvcmQyMg==
User-Agent: Neo4j.Sips client
Host: localhost:7373
Accept: application/json; charset=UTF-8
Content-Type: application/json; charset=UTF-8
X-Stream: true


==resp==
HTTP/1.1 401 Unauthorized
WWW-Authenticate: None
Date: Sun, 24 Jan 2016 16:12:22 GMT
Content-Type: application/json; charset=UTF-8

```

With the following `neo4j_sips` expected error:

```
=INFO REPORT==== 24-Jan-2016::11:12:22 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application neo4j_sips: Neo4j.Sips.start(:normal, []) returned an error: shutdown: failed to start child: :neo4j_sips_pool
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {{:badmatch, %{errors: [%{code: "Neo.ClientError.Security.AuthorizationFailed", message: "Invalid username or password."}]}}, [{Neo4j.Sips.Server, :init, 1, [file: 'lib/neo4j_sips/server.ex', line: 72]}, {Neo4j.Sips.Connection, :init, 1, [file: 'lib/neo4j_sips/connection.ex', line: 26]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
            src/poolboy.erl:275: :poolboy.new_worker/1
            src/poolboy.erl:296: :poolboy.prepopulate/3
            src/poolboy.erl:145: :poolboy.init/3
            (stdlib) gen_server.erl:328: :gen_server.init_it/6
            (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

While a proper authentication will yield the correct behavior, excerpt from the log file:

```
127.0.0.1 - - [24/Jan/2016:11:10:34 -0500] "GET /db/data/ HTTP/1.1" 200 663 "
==req== GET /db/data/ HTTP/1.1
Authorization: Basic bmVvNGo6c3dvcmQ=
User-Agent: Neo4j.Sips client
Host: localhost:7373
Accept: application/json; charset=UTF-8
Content-Type: application/json; charset=UTF-8
X-Stream: true


==resp==
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Date: Sun, 24 Jan 2016 16:10:34 GMT
Content-Type: application/json; charset=UTF-8; stream=true

{"extensions":{},"node":"http://localhost:7373/db/data/node","node_index":"http://localhost:7373/db/data/index/node", ...

```

**Comment by johnhamelink** [comment]
Hi @florinpatrascu,

> Also, are you sure your app runs in prod mode, i.e. $ MIX_ENV=prod ... ?

I'm running the app in prod mode as I'm running it on a server it's been released into with `exrm`.

I wonder if it's to do with the size of my password? It's 128 characters long? Could that possibly be a factor?

BTW, I'm on the elixir slack channel right now if you want to discuss over chat (If you feel that could help)

**Comment by johnhamelink** [comment]
For reference, I fixed this simply by deleting my `_build` directory.

**Comment by florinpatrascu** [comment]
It means the config files were not updated?! Mix?? Very weird ...

Thank you, for letting me know!

**Comment by johnhamelink** [comment]
@florinpatrascu no problem. I added that info to this issue because @arjun from Slack (@asarode on github) PM'd me to let me know he was experiencing the same thing.
