### ISSUE TITLE
getting hex dependency conflict

### ISSUE THREAD

**Issue by supriyapjoshi** [florinpatrascu/neo4j_sips#7]
Hi,
I am using latest phoenix versions and I am getting dependency conflict on "poison".
Pasting the error and my dependencies below:

 Conflict on poison 2.1.0
  mix.lock: 2.1.0
  neo4j_sips 0.1.11, 0.1.12: ~> 1.5.0
  phoenix 1.1.4: ~> 1.5 or ~> 2.0

*\* (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

I tried to resolve it by cloning the neo4j_sips repo and bumping the version of poison, but there is another dependency - 
 {:inch_ex, "~> 0.4.0", only: :docs}
which requires the specific version of poison.

**Comment by florinpatrascu** [comment]
running few tests, and I'll push the changes shortly.

**Comment by florinpatrascu** [comment]
Please check with the latest version, available at hex.pm too. Later, this week-end maybe, I'll work on a newer version to remove atomizing keys for the data returned, b/c newer `poison` lib, which it's fine.

**Comment by florinpatrascu** [comment]
dependencies updated, small refactoring in place for accommodating the newest `keys: atoms!` option behaviour, of Poison 2.x; Poison will throw an exception on decoding keys as atoms, if the atoms (names) are not already defined. Tests green.
