### ISSUE TITLE
Ecto adapter

### ISSUE THREAD

**Issue by venkatd** [florinpatrascu/neo4j_sips#8]
New to Elixir but interested in working on an Ecto adapter with this neo4j_sips as the foundation. Is there anything that needs to be added here before getting started?

Also would love some guidance on what the next steps for that would be.

Thanks

**Comment by florinpatrascu** [comment]
Hi Venkat,

Thank you for your interest. I too started this path, originally, after reading Michał Muskała's blog:[Creating Ecto Adapters](http://michal.muskala.eu/2015/07/07/creating-ecto-adapters.html). But then the more I advanced with my designs, I realized before too late, that simply implementing an Ecto driver **for Neo4j** (or for other graphdbs too) would mean stripping off the Neo4j support for critical functions; graph specific. I won't elaborate on my past efforts, but I can say this: I decided to make a very simple Elixir-Neo4j driver, a foundation if you wish, for allowing others and myself to quickly integrate Elixir/Phoenix apps with Neo4j.

If you really wish to continue your endeavour, please by all means, but first I'd kindly suggest to contact Robert Bates (@arpieb) as he was approaching a similar strategy and in my opinion he ended up with finding a better approach, that of providing a DSL interface for graph databases. Please see the [Spiro](https://github.com/arpieb/spiro) project, here on Github, and maybe you can join him in his effort?! 

Thank you very much,
Florin.

**Comment by venkatd** [comment]
Thanks for your perspective @florinpatrascu. I'll reach out to him to learn more about his experiences. My original thoughts were the following:
- We could implement the features supported by Ecto. That means basic CRUD, queries, and associations to get up and running quickly.
- For more complex queries, we could write our own DSL. I'm not a big fan of abstracting query languages too much--my goal is allow composability without obfuscating the actual query being generated.

Are there things within Ecto that can be leveraged or do you think SQL databases and Graph databases are far too different for this?

**Comment by florinpatrascu** [comment]
> We could implement the features supported by Ecto. That means basic CRUD, queries, and associations to get up and running quickly.

that's what I thought too, originally. This will boil down to translating "CRUD, queries..." to Cypher. I thought I'd rather use Cypher instead, hence the simplicity of Neo4j.Sips. And currently I am happily using Ecto+(mysqll/psql)RDB and Neo4j together, or Neo4j w/o Ecto. Hardly finding something that was modelled for a RDB and can't be modelled (and improved) as a graph. To me, graph modelling is more natural. Mind you, I am not an expert, just trying to be a good scholar.

> For more complex queries, we could write our own DSL. I'm not a big fan of abstracting query languages too much--my goal is allow composability without obfuscating the actual query being generated.

I believe [Spiro](https://github.com/arpieb/spiro) will do this?! /cc @arpieb

> Are there things within Ecto that can be leveraged or do you think SQL databases and Graph databases are far too different for this?

I do believe that SQL databases and the Graph databases are different for good reasons.

**Comment by arpieb** [comment]
@venkatd yeah, what @florinpatrascu said.  Spiro is aiming to be an Ecto analogue for graph databases.  Ecto totally rocks for table-focused relational databases, and some KV/document DBs that fully support SQL.  However, when you get into more advanced graph-based queries based on edges and properties with graph-db transformations, SQL CRUD functionality leaves a lot on the table.

If you'd like to read the README on arpieb/spiro under the 0.x branch to see where I'm going with it, and are interested in contributing, please let me know over there!

-Rob

**Comment by MachinesAreUs** [comment]
@arpieb is Spiro dead?

**Comment by arpieb** [comment]
@MachinesAreUs at least for the time being... There seemed to be little interest in it at the time I spun it up, and with Neo4j more or less being the darling in the graph DB domain, @florinpatrascu and this module seemed to meet the needs of the Elixir community at the time.

Also quite honestly between work and school I didn't have time to tackle it solo so killed off the project; nothing I hate more than to clutter GH with a partially-implemented, non-running project.  

I graduate in May, so might resurrect it along with some other ML-related work I want to do in Elixir.  [OpenCypher](https://www.opencypher.org/) has also come a long way, so maybe there is a better route than trying to implement the Gremlin DSL...?
