### ISSUE TITLE
Cypher query builder

### ISSUE THREAD

**Issue by venkatd** [florinpatrascu/neo4j_sips#9]
Not sure if this is the best place to discuss :) 

I spoke with @arpieb and because my focus is on neo4j exclusively, he suggested we collaborate some. For my own project, I needed to prototype a Cypher query builder.

Take a look at the tests:
https://gist.github.com/venkatd/03282106e369784e70d3

There are some things that are hacked at the moment. For example, placeholders are not locally bound, so if you compose queries without unique variable names, it could cause conflicts.

Let me know what you think!

**Comment by florinpatrascu** [comment]
I apologize for the delay. I looked at the gist and I have to say it is promising. Personally, I would not encourage the abuse of `|>` in this particular implementation, especially for creating the Cypher queries. I'd rather adopt the elegance of [Ecto's Query](https://hexdocs.pm/ecto/Ecto.Query.html)  DSL. So for example:

``` Elixir
new_query
  |> labels(yo: "yeah/man", dude: "nah")
  |> return([:yo])
```

could be written like this, instead:

``` Elixir
query = match, 
        labels: [yo: "yeah/man", dude: "nah"],
        return: :yo
```

Other example (converted from your gist):

``` Elixir
query = match,
        labels: [user: "user"],
        where: ["user.uuid = {uuid}", uuid: 123],
        return: :user,
        set: ["user.email = {email}", email: "john@hotmail.com"]
```

Something like that.

**Comment by venkatd** [comment]
@florinpatrascu no worries.

I opted to start with the pipeline approach when I dug into how Ecto queries were implemented. IMHO it's not an abuse of the operator but rather a layer of abstraction down. See this article for example:
https://blog.drewolson.org/composable-queries-ecto/

We would be able to take something like 

```
query = match, 
        labels: [yo: "yeah/man", dude: "nah"],
        return: :yo
```

And using the functional style, reduce it like as follows:

```
  def match(clauses) when is_list(clauses) do
    Enum.reduce new_query, fn {type, clause}, query ->
      apply(query, type, clause)
    end
  end
```

**Comment by asianfilm** [comment]
This Dockyard approach, which is pipeline oriented, is relevant to the discussion:
http://confreaks.tv/videos/elixirdaze2016-building-and-testing-api-endpoints-with-phoenix

Here's their "composable query builder for Ecto" referenced in the video:
https://github.com/DockYard/inquisitor

And the demo app from the video:
https://github.com/bcardarella/elixirdaze-api-demo

See, for example, the `build_post_query` functions here: 
https://github.com/bcardarella/elixirdaze-api-demo/blob/master/web/controllers/api/post_controller.ex

**Comment by florinpatrascu** [comment]
Hi @venkatd - I see a similar initiative, going on in this project: [ecto_neo4j](https://github.com/mattmills/ecto_neo4j), see their TODO list (excerpt): "Cypher Query Builder -- In Progress!". Maybe you're interested to see what they have so far?! HTH
